### ISSUE TITLE
Cannot run it

### ISSUE THREAD

**Issue by KrischnaGabriel** [LLLLinda/firstrade-cli#1]
Is this error supposed to happen when running firstrade on Linux Mint 20.1 Cinnamon?
installed via the npm package manager.

 (node:873364) UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function
    at readCredential (/usr/local/lib/node_modules/firstrade-cli/bin/firstrade:38:22)
    at /usr/local/lib/node_modules/firstrade-cli/bin/firstrade:23:20
    at Object.<anonymous> (/usr/local/lib/node_modules/firstrade-cli/bin/firstrade:34:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
(node:873364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:873364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by LLLLinda** [comment]
Hi,
Cannot reproduce with same machine.
Probably should use nodes above 12. Check with this
```bash 
$ cat /etc/os-release 
$ npm -v
$ node -v
```
